language: csharp
mono: none
dist: bionic
dotnet: 5.0

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - WORKING_DIR=Content

install:
  - cd $WORKING_DIR
  - dotnet restore

script:
  - dotnet build
