CREATE LOGIN [<%PROJECT_HYPHENATED_NAME%>.www]
	WITH PASSWORD = '<%ENV_PASS%>' 
GO

USE [<%PROJECT_HYPHENATED_NAME%>]
GO

CREATE USER [<%PROJECT_HYPHENATED_NAME%>.www]
	FOR LOGIN [<%PROJECT_HYPHENATED_NAME%>.www]
	WITH DEFAULT_SCHEMA = [dbo]
GO

EXEC sp_addrolemember N'db_owner', N'<%PROJECT_HYPHENATED_NAME%>.www'
GO
